# Generated by Django 3.1.7 on 2021-04-06 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_notes_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='application_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('status', models.CharField(max_length=140)),
                ('biography', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='notes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application_user'),
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
